eureka:
  client:
    service-url:
      defaultZone: http://localhost:8778/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0

#name:
#  value: nzangi
spring:
  cloud:
    config:
      override-system-properties: false